# Generated by Django 6.0.6 on 2026-06-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('electronica', 'Electrónica'), ('hogar', 'Hogar y Cocina'), ('moda', 'Moda'), ('deportes', 'Deportes'), ('libros', 'Libros'), ('otros', 'Otros')], default='otros', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de adquisición'),
        ),
    ]
